version: '3.7'
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
